# Generated by Django 4.1.7 on 2023-03-09 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoArticulos',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('SKU', models.BigIntegerField()),
                ('ImagenURL', models.URLField(max_length=500)),
                ('Nombre', models.CharField(max_length=150)),
                ('Cantidad', models.IntegerField()),
                ('FechaRegistro', models.CharField(max_length=50)),
                ('UltimaFechaActualizacion', models.CharField(max_length=50)),
                ('Sincronizado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacturacionEncabezado',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NumeroOrden', models.IntegerField()),
                ('Total', models.CharField(max_length=50)),
                ('Fecha', models.CharField(max_length=50)),
                ('Moneda', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FacturacionDetalle',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ImagenURL', models.URLField(max_length=500)),
                ('SKU', models.BigIntegerField()),
                ('Nombre', models.CharField(max_length=150)),
                ('Cantidad', models.CharField(max_length=10)),
                ('Precio', models.CharField(max_length=50)),
                ('Total', models.CharField(max_length=50)),
                ('idEncabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopifyApp.facturacionencabezado')),
            ],
        ),
        migrations.CreateModel(
            name='FacturacionCliente',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('ID', models.BigIntegerField()),
                ('Nombre', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=150)),
                ('Direccion', models.CharField(max_length=300)),
                ('idEncabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopifyApp.facturacionencabezado')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoLogArticulos',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('JSON', models.JSONField()),
                ('FechaRegistro', models.CharField(max_length=50)),
                ('idArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopifyApp.catalogoarticulos')),
            ],
        ),
    ]
