# Generated by Django 4.1.7 on 2023-03-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopifyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacioncliente',
            name='Correo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='facturacioncliente',
            name='Direccion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='facturacioncliente',
            name='ID',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='facturacioncliente',
            name='Nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='facturacioncliente',
            name='Telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
